import Header from "@/layout/Header";
import { ConvexClientProvider } from "@/providers/ConvexClientProvider";
import NexAuthSessionProvider from "@/providers/next-auth-session-provider";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: any;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={montserrat.className}>
        <NexAuthSessionProvider session={session}>
          <ConvexClientProvider>
            <Header />
            <main className="h-[calc(100vh-86px)] text-muted-foreground">
              {children}
            </main>
          </ConvexClientProvider>
        </NexAuthSessionProvider>
      </body>
    </html>
  );
}
