import { Recipe } from "@/modules/recipes/utils/types";

export const recipe: Recipe = {
  id: "0",
  title: "Meat",
  description: "Cooked meat with simple seasoning.",
  ingredients: [
    { name: "meat", quantity: 500, unit: "g" },
    { name: "pepper", quantity: 1, unit: "tsp" },
    { name: "salt", quantity: 1, unit: "tsp" },
  ],
  instructions: ["Step 1: Season the meat", "Step 2: Cook the meat on a grill"],
  prepTime: 5,
  cookTime: 10,
  totalTime: 15,
  servings: 2,
  cuisine: "American",
  difficulty: "Easy",
  nutrition: {
    calories: 250,
    fat: 15,
    protein: 20,
    carbs: 0,
  },
  imageUrl:
    "https://plus.unsplash.com/premium_photo-1663852297267-827c73e7529e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  tags: ["main", "grill"],
};

export const recipes: Recipe[] = [
  {
    id: "0",
    title: "Meat",
    description: "Cooked meat with simple seasoning.",
    ingredients: [
      { name: "meat", quantity: 500, unit: "g" },
      { name: "pepper", quantity: 1, unit: "tsp" },
      { name: "salt", quantity: 1, unit: "tsp" },
    ],
    instructions: [
      "Step 1: Season the meat",
      "Step 2: Cook the meat on a grill",
    ],
    prepTime: 5,
    cookTime: 10,
    totalTime: 15,
    servings: 2,
    cuisine: "American",
    difficulty: "Easy",
    nutrition: {
      calories: 250,
      fat: 15,
      protein: 20,
      carbs: 0,
    },
    imageUrl:
      "https://plus.unsplash.com/premium_photo-1663852297267-827c73e7529e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    tags: ["main", "grill"],
  },
  {
    id: "1",
    title: "Vegan Salad",
    description: "A fresh and healthy vegan salad.",
    ingredients: [
      { name: "lettuce", quantity: 100, unit: "g" },
      { name: "tomatoes", quantity: 2, unit: "pcs" },
      { name: "cucumber", quantity: 1, unit: "pcs" },
      { name: "olive oil", quantity: 2, unit: "tbsp" },
      { name: "lemon juice", quantity: 1, unit: "tbsp" },
    ],
    instructions: [
      "Step 1: Chop the vegetables",
      "Step 2: Mix with olive oil and lemon juice",
    ],
    prepTime: 10,
    cookTime: 0,
    totalTime: 10,
    servings: 1,
    cuisine: "Mediterranean",
    difficulty: "Easy",
    nutrition: {
      calories: 150,
      fat: 10,
      protein: 3,
      carbs: 12,
    },
    imageUrl:
      "https://plus.unsplash.com/premium_photo-1663852297267-827c73e7529e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    tags: ["side", "vegan"],
  },
  {
    id: "2",
    title: "Spaghetti Carbonara",
    description: "Classic Italian pasta dish.",
    ingredients: [
      { name: "spaghetti", quantity: 200, unit: "g" },
      { name: "eggs", quantity: 2, unit: "pcs" },
      { name: "pancetta", quantity: 100, unit: "g" },
      { name: "parmesan", quantity: 50, unit: "g" },
      { name: "black pepper", quantity: 1, unit: "tsp" },
    ],
    instructions: [
      "Step 1: Boil the spaghetti",
      "Step 2: Cook pancetta",
      "Step 3: Mix eggs, cheese, and pepper",
      "Step 4: Combine everything",
    ],
    prepTime: 10,
    cookTime: 20,
    totalTime: 30,
    servings: 4,
    cuisine: "Italian",
    difficulty: "Medium",
    nutrition: {
      calories: 600,
      fat: 25,
      protein: 20,
      carbs: 70,
    },
    imageUrl:
      "https://plus.unsplash.com/premium_photo-1663852297267-827c73e7529e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    tags: ["main", "pasta"],
  },
  {
    id: "3",
    title: "Chocolate Cake",
    description: "Rich and moist chocolate cake.",
    ingredients: [
      { name: "flour", quantity: 200, unit: "g" },
      { name: "cocoa powder", quantity: 50, unit: "g" },
      { name: "sugar", quantity: 150, unit: "g" },
      { name: "eggs", quantity: 2, unit: "pcs" },
      { name: "butter", quantity: 100, unit: "g" },
      { name: "milk", quantity: 100, unit: "ml" },
    ],
    instructions: [
      "Step 1: Mix dry ingredients",
      "Step 2: Add wet ingredients",
      "Step 3: Bake in the oven",
    ],
    prepTime: 15,
    cookTime: 45,
    totalTime: 60,
    servings: 8,
    cuisine: "Dessert",
    difficulty: "Medium",
    nutrition: {
      calories: 400,
      fat: 18,
      protein: 6,
      carbs: 55,
    },
    imageUrl:
      "https://plus.unsplash.com/premium_photo-1663852297267-827c73e7529e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    tags: ["dessert", "cake"],
  },
  {
    id: "4",
    title: "Chicken Stir-Fry",
    description: "Quick and easy chicken stir-fry.",
    ingredients: [
      { name: "chicken breast", quantity: 300, unit: "g" },
      { name: "soy sauce", quantity: 2, unit: "tbsp" },
      { name: "garlic", quantity: 2, unit: "cloves" },
      { name: "vegetables", quantity: 200, unit: "g" },
      { name: "sesame oil", quantity: 1, unit: "tbsp" },
    ],
    instructions: [
      "Step 1: Cook chicken",
      "Step 2: Stir-fry vegetables",
      "Step 3: Combine and serve",
    ],
    prepTime: 10,
    cookTime: 15,
    totalTime: 25,
    servings: 3,
    cuisine: "Asian",
    difficulty: "Easy",
    nutrition: {
      calories: 350,
      fat: 10,
      protein: 30,
      carbs: 25,
    },
    imageUrl:
      "https://plus.unsplash.com/premium_photo-1663852297267-827c73e7529e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    tags: ["main", "stir-fry"],
  },
];
